defaultPortal: thenumberco
portals:
  - name: thenumbercompany
    portalId: 341671672
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CP-Ah-rmMhIRAAUAQAAAAGwAQAJYAgEAAAgY-P31ogEg7sjhJSju6QwyFCDHV06kbxHY3ZOuX6VbB6helMSeOkwAAARBAAAAAAAAAAAAAAAAAIAAAAAAAAQAAAAAAAAAADxgUAAARAAAQPwYBgAQIAMAAAAAAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAQQhQGle-wGHEi2ODiWUD-JvHwvBhL4koDbmEzUgBaAGAAaO7I4SVwAA
        expiresAt: '2025-04-25T14:02:27.891Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTMtMjkzZS1mYjQwLTRkZTgtYjYxYy0xMTZlNjJjMjEyN2QQ-P31ogEY7sjhJSoZAAXmkYIeVzu-iyi5u-yGnOGRuNEVv5Urd0oDbmEz
  - name: thenumberco
    portalId: 341707179
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJr_o-vmMhIaAA0AQAAA4C0DQAJYAgEAAPgAAAAAAAAAAAYYq5P4ogEg7sjhJSju6QwyFN-t067a1-ZxswGK3Grp9t_p57f0Ok8AAARBAAAAeAAAAAAAAAAAAIAAAAAAAAQAAMAHAI7wMTxgEAYARABgQPwYBgAQIAMAAAAAADz-AwAAAAAAAAAMBAAAAAAAAAAAAAAQAADAQhQVrztNIAuQkZxw0twZbZw7TwtLsEoDbmEzUgBaAGAAaO7I4SVwAA
        expiresAt: '2025-04-25T14:45:19.937Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTMtNWE2OS1hZmM3LTRhMTItOWFiMC1kNjljMGE4MmY5ODQQq5P4ogEY7sjhJSoZAAXmkYIZEzidjIlPKvimGSByOT_3jZBO-EoDbmEz
