defaultPortal: thenumbercompany
portals:
  - name: thenumbercompany
    portalId: 341671672
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CP-Ah-rmMhIRAAUAQAAAAGwAQAJYAgEAAAgY-P31ogEg7sjhJSju6QwyFCDHV06kbxHY3ZOuX6VbB6helMSeOkwAAARBAAAAAAAAAAAAAAAAAIAAAAAAAAQAAAAAAAAAADxgUAAARAAAQPwYBgAQIAMAAAAAAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAQQhQGle-wGHEi2ODiWUD-JvHwvBhL4koDbmEzUgBaAGAAaO7I4SVwAA
        expiresAt: '2025-04-25T14:02:27.891Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTMtMjkzZS1mYjQwLTRkZTgtYjYxYy0xMTZlNjJjMjEyN2QQ-P31ogEY7sjhJSoZAAXmkYIeVzu-iyi5u-yGnOGRuNEVv5Urd0oDbmEz
