defaultPortal: thenumbercompany
portals:
  - name: thenumbercompany
    portalId: 341671672
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMKG0OnmMhIRAAUAQAAAAGwAQAJYAgEAAAgY-P31ogEg7sjhJSju6QwyFEFwV23lCsr4X1o-uC4fMxYUViZgOkwAAARBAAAAAAAAAAAAAAAAAIAAAAAAAAQAAAAAAAAAADxgUAAARAAAQPwYBgAQIAMAAAAAAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAQQhTD-GEzIrg7E3uRPoeSSLXx99dBcEoDbmEzUgBaAGAAaO7I4SVwAA
        expiresAt: '2025-04-25T13:47:27.484Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTMtZmEyOS0xZGUyLTQxOGUtYWEzYi0wNjU3MWNmMTBkYzUQ-P31ogEY7sjhJSoZAAXmkYLZJKcx1FCvPoWAz4xW6tHog3p3q0oDbmEz
